### ISSUE TITLE
Taxononmic filtering using --Inv not working?

### ISSUE THREAD

**Issue by nerdbrained** [blobtoolkit/blobtoolkit#184] opened 2023-09-11 20:10 UTC
I'm working with some fish genome assemblies in Blobtools. The scaffolds from out unfiltered assemblies mostly have hits to Chordata but also to multiple other phyla, including several bacterial phyla and other potential contaminants. Filtering by GC content and coverage gets rid of most of those, which is good, but I still have scaffolds with hits to Arthropoda, Annelida, Mollusca, Porifera, and Bryozoa.

I have tried filtering these out in one shot using  "--param bestsumorder_phylum--Inv=Chordata", but this still leaves all of the scaffolds with hits to Arthropoda, Annelida, Mollusca, Porifera, and Bryozoa.  I can successfully filter those out with "--param bestsumorder_phylum--Keys=Arthropoda,Annelida,Mollusca,Porifera,Bryozoa" but it would be great to have --Inv function as intended for working with future assemblies.

**Comment by rjchallis** [comment] 2023-09-13 10:04
Thanks for letting me know about the problem with `--Inv`. I'll take a look at this to see why it isn't working. In the meantime you may be able to get a similar result by using the `--invert` flag to invert the entire filter like `--param bestsumorder_phylum=Chordata --invert`. 

Unfortunately this would also reverse the effects of any other filters you apply at the same time so you would have to also swap, e.g. `--param gc--Min 0.5` for `--param gc--Max 0.5`.

**Comment by rjchallis** [comment] 2023-09-14 15:04
This should be working as expected in the 4.2.1 release

**Comment by myco-bradshaw** [comment] 2023-12-01 01:37
Hello, this still seems to be an issue even when installing with pip from the latest release. the --Inv tag when used in conjunction with --param no errors out, and when using --invert for the whole command still leads to improperly filtered taxa.

**Comment by rjchallis** [comment] 2023-12-05 09:23
Thanks for the extra details. 

For the first command, `--param bestsumorder_superkingdom--Inv=no-hit` keeps only those sequences that are labelled as no-hit at the superkingdom level. This means that these sequences will have no blast hits at all and will be no-hit at any taxonomic rank.  `--param bestsumorder_kingdom--Inv=Fungi` keeps the subset of those sequences that are labelled as Fungi, but there cannot be any overlap between no-hit and Fungi so the list is empty. This then leads to the error that you encountered, which is something I should catch and give a more informative message for.  

You should be able to get the list of sequences that are labelled as only no-hit or Fungi by combining the 2 options and using only the kingdom level labels so `--Inv` works on the combined set, e.g.

```
blobtools filter
--param bestsumorder_kingdom--Inv=no-hit,Fungi
...
```

The output that you are seeing for the second command looks like it is probably correct - the taxonomic labels are assigned based on the cumulative hits at a given rank so it is possible (and reasonably common) for some sequences to be assigned to a phylum that is not part of the same kingdom as the kingdom label. If there are 3 hits to Fungi and 2 to Metazoa, the kingdom level assignment will be Fungi, but at the phylum level, those hits could be 1 each to Ascomycota, Basidiomycota and Chytridiomycota but 2 to Chordata so the sequence would be labelled Chordata.

**Comment by git-hobo** [comment] 2023-12-18 16:44
Hello!
**The Problem**
I am basically trying to do the same filtering operation as the mushroom-person, that posted previously. I generated my blobdirs by running the whole pipeline with the docker container (4.2.0). I am now trying to filter my PacBio Hifi reads, keeping only no-hit and Arthropoda reads to assemble once again. When instantiating the container I am mounting the output directory of the pipeline run to the /blobtoolkit/output/ directory in the container. I then untar and unzip the BlobDir, which is then located at /blobtoolkit/output/sample/sample. I continue by running ```blobtools filter``` like this:
```bash
blobtools filter \
    --invert \
    --param buscoregions_phylum--Keys=Arthropoda,no-hit \
    --fastq ./sample.fq.gz \
    --cov ./sample/sample.sample.bam \
    --output ./sample_filterout \
    /blobtoolkit/output/sample/sample
```
This works without throwing errors, but it always creates and empty .fastq file by the name ```sample.filtered.fq.gz```.

**First Observation**
I also looked at the ```--table``` outputs with the above specified ```--param``` with and without ```--invert```. The contig table seems to be mostly correctly filtered, but there are ```no-hit``` contigs in both the normal and inverted filter condition tables. I am guessing this has something to do with me using ```buscoregions``` for filtering and the table displaying ```buscogenes``` for annotation, or something like that?

**Second Observation**
I redirected the screen output of read-IDs to text files with regular and inverted filter conditions, compared the IDs and got the following results:
```bash
inverted filters:    3353080 read-IDs
regular filters:      160290 read-IDs
intersection:          49836 read-IDs
````
My expectation would be no intersection between read-IDs for a filtering condition and its inverse. What am I missing here? I seem to be misunderstanding how this whole thing works.

**Closed** 2023-12-20 09:17 UTC

**Comment by rjchallis** [comment] 2023-12-21 14:31
Hi I'm not clear why this is creating an empty file - I'm running similar commands and getting the expected output. Could you share a few lines of your fastq files so I can check if it is an issue with parsing the specific format of your file.

**First observation**
Yes this is likely due to filtering with one tax rule and displaying the other. The buscogenes tax rule will only return hits for contains with at least one busco gene so will likely have more no-hit contains than the buscoregions rule. To display both in the table output you can add more columns by specifying `--table-fields plot,buscoregions_phylum` as part of the filter command (`plot` is shorthand for the 4 default columns that would be part of the blob plot).

**Second observation**
The filter is based on reads that map to the sequences that match your params. The BAM file is not filtered to remove multi mapped reads so the overlapping read sets are likely due to some reads mapping to more than one contig.

**Comment by git-hobo** [comment] 2024-01-18 20:19
I have fixed my empty FASTQ output file problem mentioned above:
Apparently ```blobtoolkit``` does not work with FASTQ headers which contain the ```/```character. I have reformatted my FASTQ headers so that they do not contain ```/``` and now it works. If you are using ```DeepConsensus``` and ```ccs``` for your PacBio Hifi reads there is a good chance that your FASTQ headers will have ```/``` in it.

**Comment by rjchallis** [comment] 2024-01-19 09:30
Thanks for sharing a solution to this problem. Now I know what the issue is, I'll work on getting it fixed in the next release

**Comment by rjchallis** [comment] 2024-02-01 14:46
@git-hobo I fixed the problem line so these headers should be fine with version 4.3.4
